version: '3.9'

services:
  user_service_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${USER_SERVICE_DATABASE_PASSWORD}
      POSTGRES_USER: ${USER_SERVICE_DATABASE_USER}
      POSTGRES_DB: ${USER_SERVICE_DATABASE_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DATABASE_USER} -d ${USER_SERVICE_DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: