version: '3.9'

services:

  user-service:
    build: .
    env_file: .env
    ports:
      - "${APP_PORT}:80"
    depends_on:
      user-service-db:
        condition: service_healthy
    networks:
      - user-service-net
    restart: unless-stopped

  user-service-db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${USER_SERVICE_DATABASE_PASSWORD}
      POSTGRES_USER: ${USER_SERVICE_DATABASE_USER}
      POSTGRES_DB: ${USER_SERVICE_DATABASE_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_SERVICE_DATABASE_USER} -d ${USER_SERVICE_DATABASE_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - user-service-net

networks:
  user-service-net:
    driver: bridge

volumes:
  postgres-data: