services:
  user-service:
    build: .
    env_file: .env
    ports:
      - "${USER_SERVICE_APP_PORT}:80"
    depends_on:
      - user-service-db
    networks:
      - user-service-net
      - backend-net

  user-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${USER_SERVICE_DATABASE_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_DATABASE_PASSWORD}
      POSTGRES_DB: ${USER_SERVICE_DATABASE_DB}
    ports:
      - "${USER_SERVICE_DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - user-service-net

volumes:
  postgres-data:

networks:
  user-service-net:
  backend-net:
    external: true